# Generated by Django 3.2.4 on 2021-06-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
